=== Javiermder/EjerciciosLMSGI/EXAMEN COCTELERIA/2018/dtd-cocteleria.dtd
<!ELEMENT cocteleria (bebidas)>
<!ELEMENT bebidas (con, sin)>
<!ELEMENT con (roncola, gyntonic)>
<!ELEMENT roncola (ingredientes)>
<!ELEMENT gyntonic (ingredientes)>
<!ELEMENT ingredientes (alcohol, refresco, fruta?)>
<!ELEMENT alcohol (#PCDATA)>
<!ELEMENT refresco (#PCDATA)>
<!ELEMENT fruta (#PCDATA)>
<!ELEMENT sin ANY>
<!ATTLIST cocteleria direccion CDATA #IMPLIED 
                      nombre CDATA #REQUIRED
                      telefono CDATA #FIXED "957525789">
<!ENTITY % atributoCoste "coste CDATA #IMPLIED"> 
<!ATTLIST roncola %atributoCoste;>
<!ATTLIST gyntonic %atributoCoste;>

=== Javiermder/EjerciciosLMSGI/EXAMEN COCTELERIA/2018/cocteleria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cocteleria SYSTEM "dtd-cocteleria.dtd">
<cocteleria direccion="Plaza Nueva" nombre="LACoctail" telefono="957525789">
   <bebidas>
    <con>
        <roncola coste = "5">
            <ingredientes>
                <alcohol>Ron</alcohol>
                <refresco>Cocacola</refresco>
                <fruta>si</fruta>
            </ingredientes>
        </roncola>
        <gyntonic coste = "5">
            <ingredientes> 
                <alcohol>Lariosa</alcohol>
                <refresco>Tonica</refresco>
            </ingredientes> 
        </gyntonic>

    </con>
    <sin>

    </sin>
   </bebidas>
</cocteleria>
